name_or_path: lomahony/pythia-2.8b-helpful-sft-3epochs
tokenizer_name_or_path: null
archive: null
block_name: GPTNeoXLayer

policy_dtype: bfloat16 #float32
fsdp_policy_mp: null
reference_dtype: float16